# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '100React' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 100React
  pod 'KeychainSwift', '~> 17.0'

  target '100ReactTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
